import com.google.gson.Gson;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */

public class friendsrequest extends javax.swing.JInternalFrame {

    Streams stream;
    String LoggedinUserName;
    friendwishlist jtRowData;
    /* * Creates new form friendsrequest
     */
    public friendsrequest(Streams stream) {
        initComponents();
        this.stream = stream;
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui =(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        LoggedinUserName = Streams.myUsername; //da keda esm el user ele 3amel Login
        
        UserDTO objFriendRequests = new UserDTO();
        objFriendRequests.tag="ViewFriendRequests";
        objFriendRequests.username=LoggedinUserName;
        String data = new Gson().toJson(objFriendRequests);
        stream.pos.println(data);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        friendRequestsTable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(610, 400));

        friendRequestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Friend Requests"
            }
        ));
        friendRequestsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                friendRequestsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(friendRequestsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                    .addGap(57, 57, 57)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void friendRequestsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_friendRequestsTableMouseClicked
        int index =friendRequestsTable.getSelectedRow(); //get row index
        String fRequestname = friendRequestsTable.getValueAt(index, 0).toString();
        //System.out.println(fRequestname);

        UserDTO objAcceptOrReqjectRequest = new UserDTO();
        objAcceptOrReqjectRequest.FriendReqName =fRequestname;
        objAcceptOrReqjectRequest.username=Streams.myUsername;
        String[] choices= {"Accept","Reject"};
        int response=JOptionPane.showOptionDialog(this, "Do you want to add "+ fRequestname +" as a new friend?","Friend Request",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.QUESTION_MESSAGE, null,
            choices, choices[0]);
        if(response == 0) //Accept
        {
            objAcceptOrReqjectRequest.tag="AcceptFRequest";
            Object[] options = {"OK"};
            int n = JOptionPane.showOptionDialog(this,fRequestname +
                " Has been added Sucessfuly to your friend list!" ,"Friend Request Accepted",
                JOptionPane.PLAIN_MESSAGE,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);
        }
        else if( response ==1) //Reject
        {
            objAcceptOrReqjectRequest.tag="RejectFRequest";
        }
        else  //Did not choose any of them
        {
            objAcceptOrReqjectRequest.tag="NoThingFRequest";
        }
        String data = new Gson().toJson(objAcceptOrReqjectRequest);
        stream.pos.println(data);
    }//GEN-LAST:event_friendRequestsTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable friendRequestsTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
