import com.google.gson.Gson;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
public class myfriends extends javax.swing.JInternalFrame {
    Streams stream;
    String LoggedinUserName;
    friendwishlist jtRowData;
    /**
     * Creates new form myfriends
     */
    public myfriends(Streams stream) {
        initComponents();
        this.stream = stream;
        System.out.println("myfriends stream is "+stream);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui =(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        jTextField1.setEditable(false);
        LoggedinUserName = Streams.myUsername; //da keda esm el user ele 3amel Login
        
        UserDTO objFriends = new UserDTO();
            objFriends.tag="ViewMyFriendList";
            objFriends.username=LoggedinUserName;
            //stream.myUsername =LoggedinUserName;
            String data = new Gson().toJson(objFriends);
            System.out.println(data);
            stream.pos.println(data);
 
        jtRowData= new friendwishlist(stream);
    }
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        friendsTable = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(610, 400));

        friendsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "List of Friends"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        friendsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                friendsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(friendsTable);

        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("Enter Your Friend's UserName");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 69, 129));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-delete-15.png"))); // NOI18N
        jButton1.setText("Remove");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 69, 129));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-friends-15.png"))); // NOI18N
        jButton2.setText("Add Friends");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
       
        addfriend friend = new addfriend(stream);
        friend.setVisible(true);
        friend.pack();
        friend.setLocationRelativeTo(null);     
        // to move add frame 
    }//GEN-LAST:event_jButton2MouseClicked
    
    private void friendsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_friendsTableMouseClicked
                                    
                 int index =friendsTable.getSelectedRow(); /// el row aly ana wa2fa 3ndo (index,0)
                 String name = friendsTable.getValueAt(index, 0).toString();
                 jTextField1.setText(name);
                 System.out.println(name);
                 //RADWA
                 UserDTO regFrienWishList = new UserDTO(); 
                 regFrienWishList.tag="BringFriendWishList";
                 regFrienWishList.username=Streams.myUsername;
                 regFrienWishList.Friendname=name;
                 String data = new Gson().toJson(regFrienWishList);
                 stream.pos.println(data);
                 
                 jtRowData.setVisible(true);
                 jtRowData.pack();
                 jtRowData.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                 
                 
              ///]///////////////////////////////////////////////
////                 TableModel model = friendsTable.getModel();
////                 String name = model.getValueAt(index, 0).toString();
////                 UserDTO regFrienWishList = new UserDTO(); 
////                 regFrienWishList.tag="BringProductData";
//                 regFrienWishList.username=Streams.myUsername;
//                 
//                 String data = new Gson().toJson(regFrienWishList);
//                 stream.pos.println(data);
                 
       
//               int index =friendsTable.getSelectedRow();
//                 jtRowData.setVisible(true);
//                 jtRowData.pack();
//                 jtRowData.setDefaultCloseOperation(PROPERTIES);// to show friends
    }//GEN-LAST:event_friendsTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jTextField1.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please, Enter your friend's Username", "Remove a Friend", JOptionPane.INFORMATION_MESSAGE);

        }
        else
        {
            UserDTO objFriends = new UserDTO();
            objFriends.tag="RemoveFriend";
            objFriends.username=LoggedinUserName;
            objFriends.RemoveFriend = jTextField1.getText();
            //stream.myUsername =LoggedinUserName;
            String data = new Gson().toJson(objFriends);
            System.out.println(data);
            stream.pos.println(data);

            Object[] options = {"OK"};
            int n = JOptionPane.showOptionDialog(this,jTextField1.getText() +
                       " has been removed successfully! " ,"Remove Friend",
                       JOptionPane.PLAIN_MESSAGE,
                       JOptionPane.QUESTION_MESSAGE,
                       null,
                       options,
                       options[0]);
            
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
            if(jTextField1.getText().equals("Enter Your Friend's UserName"))
            {
                jTextField1.setText("");
                jTextField1.setForeground(new Color(153,153,153));
            }// TODO add your handling code here:
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        if(jTextField1.getText().equals(""))
            {
                jTextField1.setText("Enter Your Friend's UserName");
                jTextField1.setForeground(new Color(153,153,153));
            }//// TODO add your handling code here:
    }//GEN-LAST:event_jTextField1FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable friendsTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
